version: '3.1'

services:
  web:
    build:
      context: ./configs
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
      UID: 1000
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 80:80
    stdin_open: true
    tty: true
    networks:
      shared:
        ipv4_address: 172.18.0.2
  db:
    restart: unless-stopped
    environment:
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: appuser
      MYSQL_USER: appuser
      MYSQL_PASSWORD: appuser
      MYSQL_ROOT_HOST: "%"
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      shared:
        ipv4_address: 172.18.0.3
networks:
  shared:
    external:
      name: shared
